app = "trading-bot-d-pngg"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "off"
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ["app"]

[processes]
  app = "python bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
